on: [push]

name: CreatePDFs

jobs:
  makepdfs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy md files to doc directory
      run: |
        mkdir doc tmp
        find . -type f -name '*.md' | xargs cp -t doc/
    - uses: mkrakowitzer/actions-makepdfs@master
      if: github.ref == 'refs/heads/master'
    - name: clean up of generated files
      run: |
        mv tmp/*.pdf .
        rm -f doc/*
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.pdf
        git commit -m "[Automated] Added PDF files"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
